import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import dateFormat from "dateformat";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home({ data, error }) {
  console.log("data :>> ", data);

  const router = useRouter();

  useEffect(() => {
    console.log("proces.env.BASE_URL :>> ", process.env.BASE_URL);
  }, []);

  const handleNavigation = (element) => {
    console.log(element);
    router.push("/" + element.slug);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.innerContent}>
          <h1>Available Campaigns</h1>
          {error && <p>{error}</p>}
          {data.map((element) => (
            <div key={element.slug}>
              <div
                className={styles.item}
                onClick={() => handleNavigation(element)}
              >
                <div className={styles.imgContainer}>
                  <Image
                    src={`${process.env.CLOUDFOUNDRY_URL}` + "/" + element.logo}
                    height={120}
                    width={120}
                    alt="Campaign Banner"
                    className={styles.img}
                  />
                </div>
                <div className={styles.rightItems}>
                  <Link href={"/" + element.slug}>
                    <a>{element.title}</a>
                  </Link>
                  <p>{element.description}</p>
                  {
                    <small>
                      {dateFormat(
                        new Date(element.created_at),
                        "dddd, mmmm, dS, yyyy"
                      )}
                    </small>
                  }
                </div>
              </div>
            </div>
          ))}
        </div>
      </main>
      {/* <footer className={styles.footer}></footer> */}
    </>
  );
}

// curl -X GET "http://127.0.0.1:8000/api/campaigns/" -H  "accept: application/json" -H  "X-CSRFToken: PutW5y9Ssrj4MUrDSzq5CVRvPnLrz2Qh1EJmHMr05niMQTDiCeIUkvRQ3dYhHUHJ"
export async function getStaticProps() {
  let data = [];
  let error = null;
  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/campaigns/`
    );
    data = await response.json();
  } catch (err) {
    console.log("data :>> ", err);
    error = err.message ? err.message : "Something went wrong";
  }

  return {
    props: {
      data,
      error,
    },
  };
}
